language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('stopwords'); nltk.download('wordnet')"
# command to run tests
script:
  - pytest